2025-02-26 12:14:53,399 INFO    MainThread:26184 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-26 12:14:53,399 INFO    MainThread:26184 [wandb_setup.py:_flush():67] Configure stats pid to 26184
2025-02-26 12:14:53,399 INFO    MainThread:26184 [wandb_setup.py:_flush():67] Loading settings from C:\Users\oleks\.config\wandb\settings
2025-02-26 12:14:53,399 INFO    MainThread:26184 [wandb_setup.py:_flush():67] Loading settings from d:\University\Diploma\wandb\settings
2025-02-26 12:14:53,399 INFO    MainThread:26184 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-26 12:14:53,399 INFO    MainThread:26184 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\University\Diploma\wandb\run-20250226_121453-g7m447ft\logs\debug.log
2025-02-26 12:14:53,400 INFO    MainThread:26184 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\University\Diploma\wandb\run-20250226_121453-g7m447ft\logs\debug-internal.log
2025-02-26 12:14:53,400 INFO    MainThread:26184 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000265F6C47E30>
2025-02-26 12:14:53,400 INFO    MainThread:26184 [wandb_init.py:init():761] calling init triggers
2025-02-26 12:14:53,400 INFO    MainThread:26184 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0007, 'architecture': 'CNN', 'dataset': 'custom-dataset', 'epochs': 5, '_wandb': {}}
2025-02-26 12:14:53,400 INFO    MainThread:26184 [wandb_init.py:init():784] starting backend
2025-02-26 12:14:53,400 INFO    MainThread:26184 [wandb_init.py:init():788] sending inform_init request
2025-02-26 12:14:53,479 INFO    MainThread:26184 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-26 12:14:53,481 INFO    MainThread:26184 [wandb_init.py:init():803] backend started and connected
2025-02-26 12:14:53,483 INFO    MainThread:26184 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-02-26 12:14:53,503 INFO    MainThread:26184 [wandb_init.py:init():896] updated telemetry
2025-02-26 12:14:53,559 INFO    MainThread:26184 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-26 12:14:54,038 ERROR   MainThread:26184 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "d:\Programs\Python\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\Lib\site-packages\wandb\sdk\wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity my-awesome-diploma-team not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
